### ISSUE TITLE
Mismatch in array sizes

### ISSUE THREAD

**Issue by bjhardcastle** [AllenInstitute/npc_ephys#1]
```python
(npc_ephys-3.11) C:\Users\ben.hardcastle\github\npc_ephys>python  
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import npc_ephys
>>> import npc_lims
>>> device_timing_on_sync = npc_ephys.openephys.get_ephys_timing_on_sync(npc_lims.get_h5_sync_from_s3('662892_20230821'), npc_lims.get_recording_dirs_experiment_path_from_s3('662892_20230821'), only_devices_including='ProbeA')
>>> units = make_units_table_from_spike_interface_ks25('662892_20230821', device_timing_on_sync)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'make_units_table_from_spike_interface_ks25' is not defined
>>> units = npc_ephys.make_units_table_from_spike_interface_ks25('662892_20230821', device_timing_on_sync)
C:\Users\ben.hardcastle\github\npc_ephys\.venv\Lib\site-packages\npc_lims\metadata\codeocean.py:176: UserWarning: There is more than one asset for session = '662892_2023-08-21'. Defaulting to most recent: ('ecephys_662892_2023-08-21_12-43-45_sorted_2024-02-24_07-05-16', 'ecephys_662892_2023-08-21_12-43-45_sorted-ks2.5_2023-08-25_16-23-02')
  warnings.warn(
fetching units:   0%|                                 | 0/1 [00:00<?, ?device/s]662892_2023-08-21 Neuropix-PXI-100.ProbeA-AP
fetching units:   0%|                                 | 0/1 [00:08<?, ?device/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ben.hardcastle\github\npc_ephys\src\npc_ephys\units.py", line 254, in make_units_table_from_spike_interface_ks25   
    raise e from None
  File "C:\Users\ben.hardcastle\github\npc_ephys\src\npc_ephys\units.py", line 246, in make_units_table_from_spike_interface_ks25   
    _ = future.result()
        ^^^^^^^^^^^^^^^
  File "C:\Users\ben.hardcastle\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result       
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ben.hardcastle\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result 
    raise self._exception
  File "C:\Users\ben.hardcastle\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\ben.hardcastle\github\npc_ephys\src\npc_ephys\units.py", line 158, in _device_helper                       
    awc = get_amplitudes_waveforms_channels_ks25(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ben.hardcastle\github\npc_ephys\src\npc_ephys\units.py", line 73, in get_amplitudes_waveforms_channels_ks25
                                                                  
    len(sparse_channel_indices) == _templates_mean.shape[2]       
AssertionError: Expected len(sparse_channel_indices)=383 channels to match
_templates_mean.shape[2]=384
```

- happens for multiple sessions
- `sparse_channel_indices` comes from `recording_info/recording_attributes.json`
- `_templates_mean` comes from `postprocessed/templates_average.npy` or from the nwb
units table

@alejoe91 can you explain this mismatch in sizes with the new pipeline?

**Comment by alejoe91** [comment]
Yep! 

If you load the templates from the npy files, it should be no problem. The problem is when you load it from the NWB file.
Since each NWB file will store multiple streams and it likely that different probes will have different bad channels, the waveforms in the nwb file are padded to the 384 original number of channels (ragged arrays are not supported for the waveforms_mean and SD columns). This should explain the mismatch.

Does it make sense?

**Comment by bjhardcastle** [comment]
Ahh yes it does - then I think we just index into the padded 384 NWB array with the sparse channel indices.
